### ISSUE TITLE
木桶布局中的图片添加margin布局就会打乱

### ISSUE THREAD

**Issue by Kaol-Fu** [LucaslEliane/photoAlbum#1]
Hello，我在CSDN上找过来的。想请教个问题，目前木桶布局中除了行与行之间是有间隔的外，图片与图片之间是没有间隔的。如果我给图片加入margin后，整个布局就乱了。不知有没有什么好办法实现呢？我想破了脑袋也没想出来:(

**Comment by LucaslEliane** [comment]
这个代码是当时学习的时候写的。比较粗糙。不好意思给你造成困扰了。。
如果需要为图片加上间隔，我觉得使用padding增加内边距，然后设置box-sizing可以达到不打乱布局并且添加边距的方法，比如：

```css
img {
  padding: 0 12px;
  box-sizing: border-box;
}
```
